ame: live Uat Environment
on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - if: github.ref == 'refs/heads/main'
        name: uat environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd /home/rehan/nodejs
          git pull origin main
          npm install
          pm2 restart nodejs
